name: Solal system workflow
on:
    push:
        branches: 
            - main
            - 'feature/*'

jobs:
    unit-testing:
        name: This is unit testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4 
              
            - name: Setup NodeJs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            
            - name: Install dependencies
              run: npm install
              
            - name: Unit testing
              run: npm test

