name: Solal system workflow
on:
    workflow_dispatch: 
    push:            
        branches: 
            - main
            - 'feature/*'       

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}               
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:
    unit-testing:
        name: This is unit testing
        strategy:
            matrix:
                nodejs_versions: [18, 19, 20]
                os: [ubuntu-latest, macos-latest]
                exclude:
                    - nodejs_versions: 18
                      os: macos-latest

        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4 
              
            - name: Setup NodeJs-${{ matrix.nodejs_versions }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_versions }}
            
            - name: Install dependencies
              run: npm install
              
            - name: Unit testing
              run: npm test

            - name: Upload a file               # upload test cases file
              uses: actions/upload-artifact@v4
              with:
                name: test-result
                path: test-results-${{ matrix.nodejs_versions }}-${{ matrix.os }}.xml


